### ISSUE TITLE
OS error

### ISSUE THREAD

**Issue by ghost** [PacktPublishing/Artificial-Intelligence-with-Python#20]
I'm getting this error when I run the code same with regressor_multivar.py

PS E:\Python> & C:/Users/rickz/anaconda3/python.exe "e:/Python/Artificial-Intelligence-with-Python/Chapter 02/code/regressor_singlevar.py"
Traceback (most recent call last):
  File "e:/Python/Artificial-Intelligence-with-Python/Chapter 02/code/regressor_singlevar.py", line 12, in <module>
    data = np.loadtxt(input_file, delimiter=',')
  File "C:\Users\rickz\AppData\Roaming\Python\Python37\site-packages\numpy\lib\npyio.py", line 981, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "C:\Users\rickz\AppData\Roaming\Python\Python37\site-packages\numpy\lib\_datasource.py", line 269, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\Users\rickz\AppData\Roaming\Python\Python37\site-packages\numpy\lib\_datasource.py", line 623, in open
    raise IOError("%s not found." % path)
OSError: data_singlevar_regr.txt not found.

**Comment by bigearsjonny** [comment]
The file "data_singlevar_regr.txt"  is located here: https://github.com/PacktPublishing/Artificial-Intelligence-with-Python/tree/master/Chapter%2002/code
you need to download it and drop it into the same directory your python source file is located.
