### ISSUE TITLE
ch02/income_classifier throws bad_shape error

### ISSUE THREAD

**Issue by hukuzatuna** [PacktPublishing/Artificial-Intelligence-with-Python#5]
In [3]: runfile('C:/Users/Phil/src/Python/Artificial-Intelligence-with-Python/Chapter 02/code/income_classifier.py', wdir='C:/Users/Phil/src/Python/Artificial-Intelligence-with-Python/Chapter 02/code')
Reloaded modules: utilities
F1 score: 70.82%
Traceback (most recent call last):

  File "<ipython-input-3-a8c74d0f5d71>", line 1, in <module>
    runfile('C:/Users/Phil/src/Python/Artificial-Intelligence-with-Python/Chapter 02/code/income_classifier.py', wdir='C:/Users/Phil/src/Python/Artificial-Intelligence-with-Python/Chapter 02/code')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Phil/src/Python/Artificial-Intelligence-with-Python/Chapter 02/code/income_classifier.py", line 78, in <module>
    input_data_encoded[i] = int(label_encoder[count].transform(input_data[i]))

  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py", line 128, in transform
    y = column_or_1d(y, warn=True)

  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 614, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))

ValueError: bad input shape ()

**Comment by SuuSoJeat** [comment]
Me too

**Comment by SuuSoJeat** [comment]
/home/suusojeat/PycharmProjects/ArtificialIntelligencePrateekJoshi/venv/bin/python /home/suusojeat/PycharmProjects/ArtificialIntelligencePrateekJoshi/income_classifier.py
/home/suusojeat/PycharmProjects/ArtificialIntelligencePrateekJoshi/venv/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
F1 score: 71.35%
Traceback (most recent call last):
  File "/home/suusojeat/PycharmProjects/ArtificialIntelligencePrateekJoshi/income_classifier.py", line 164, in <module>
    input_data_encoded[i] = int(label_encoder[count].transform(input_data[i]))
  File "/home/suusojeat/PycharmProjects/ArtificialIntelligencePrateekJoshi/venv/lib/python3.6/site-packages/sklearn/preprocessing/label.py", line 128, in transform
    y = column_or_1d(y, warn=True)
  File "/home/suusojeat/PycharmProjects/ArtificialIntelligencePrateekJoshi/venv/lib/python3.6/site-packages/sklearn/utils/validation.py", line 614, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape ()

Process finished with exit code 1

**Comment by SuuSoJeat** [comment]
`/home/suusojeat/PycharmProjects/ArtificialIntelligencePrateekJoshi/venv/bin/python /home/suusojeat/PycharmProjects/ArtificialIntelligencePrateekJoshi/income_classifier.py
/home/suusojeat/PycharmProjects/ArtificialIntelligencePrateekJoshi/venv/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
F1 score: 71.35%
Traceback (most recent call last):
  File "/home/suusojeat/PycharmProjects/ArtificialIntelligencePrateekJoshi/income_classifier.py", line 164, in <module>
    input_data_encoded[i] = int(label_encoder[count].transform(input_data[i]))
  File "/home/suusojeat/PycharmProjects/ArtificialIntelligencePrateekJoshi/venv/lib/python3.6/site-packages/sklearn/preprocessing/label.py", line 128, in transform
    y = column_or_1d(y, warn=True)
  File "/home/suusojeat/PycharmProjects/ArtificialIntelligencePrateekJoshi/venv/lib/python3.6/site-packages/sklearn/utils/validation.py", line 614, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape ()

Process finished with exit code 1
`

**Comment by SuuSoJeat** [comment]
> /home/suusojeat/PycharmProjects/ArtificialIntelligencePrateekJoshi/venv/bin/python /home/suusojeat/PycharmProjects/ArtificialIntelligencePrateekJoshi/income_classifier.py
/home/suusojeat/PycharmProjects/ArtificialIntelligencePrateekJoshi/venv/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
F1 score: 71.35%
Traceback (most recent call last):
  File "/home/suusojeat/PycharmProjects/ArtificialIntelligencePrateekJoshi/income_classifier.py", line 164, in <module>
    input_data_encoded[i] = int(label_encoder[count].transform(input_data[i]))
  File "/home/suusojeat/PycharmProjects/ArtificialIntelligencePrateekJoshi/venv/lib/python3.6/site-packages/sklearn/preprocessing/label.py", line 128, in transform
    y = column_or_1d(y, warn=True)
  File "/home/suusojeat/PycharmProjects/ArtificialIntelligencePrateekJoshi/venv/lib/python3.6/site-packages/sklearn/utils/validation.py", line 614, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape ()

Process finished with exit code 1

**Comment by SuuSoJeat** [comment]
I found the solution -- not sure whether it's best practice.
Change the following lines of code:
`input_data_encoded[i] = int(label_encoder[count].transform(input_data[i]))`
to
`input_data_encoded[i] = int(label_encoder[count].transform([input_data[i]]))`
and
`input_data_encoded = np.array(input_data_encoded)`
to
`input_data_encoded = np.array(input_data_encoded).reshape(1, -1)`

**Comment by satiayuga** [comment]
Hi, I did your solution, but now i have this error:
   input_data_encoded[i] = label_encoder[count].transform([input_data[i]])
  File "C:\Python35\lib\site-packages\sklearn\preprocessing\label.py", line 133, in transform
    raise ValueError("y contains new labels: %s" % str(diff))
ValueError: y contains new labels: ['Tuesday']

You can help me please?

**Comment by kylek29** [comment]
@SuuSoJeat 

That fixed it for me. Maybe do a commit of the fix? See if they'll roll it in.

@satiayuga 
You'd need to post more of your script so we can see where 'Tuesday' is being introduced. The income_data.txt file doesn't contain it, so it's not being created as a label when it builds the model. When you do the Predict Output part (get a prediction for a given person), you have to use labels it already knows.

For example, if I change:
`input_data = ['37', 'Private', '215646', 'HS-grad', '9', 'Never-married', 'Handlers-cleaners', 'Not-in-family', 'White', 'Male', '0', '0', '40', 'United-States']
`
to
`input_data = ['37', 'Private', '215646', 'HS-grad', '9', 'Never-married', 'Handlers-cleaners', 'Not-in-famil', 'White', 'Male', '0', '0', '40', 'United-States']
`
^^ I changed "Not-in-family" to "Not-in-famil"

I get that same error, except stating my "Not-in-famil" label doesn't exist. The error is telling us that the model doesn't know what that label is and thus can't map it to a value to make a prediction.

**Comment by argctl** [comment]
@SuuSoJeat
You can also fix the second issue with the same method:
`predicted_class = classifier.predict([input_data_encoded])`
