### ISSUE TITLE
Artificial-Intelligence-with-Python/Chapter 03/code/traffic_prediction.py

### ISSUE THREAD

**Issue by satiayuga** [PacktPublishing/Artificial-Intelligence-with-Python#9]
Good Day!
Hi, i have a problem in line #52  of traffic_prediction.py.  Please, you can help me to resolve this error?

test_datapoint_encoded[i] = int(label_encoder[count].transform(test_datapoint[i]))
  File "C:\Python35\lib\site-packages\sklearn\preprocessing\label.py", line 128, in transform
    y = column_or_1d(y, warn=True)
  File "C:\Python35\lib\site-packages\sklearn\utils\validation.py", line 614, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape ()

Best Regards!

**Comment by baz-thepanther** [comment]
Solution:
Change the line to:
test_datapoint_encoded[i] = int(label_encoder[i].transform([test_datapoint[i]]))

**Comment by villanuevabanessa** [comment]
Hello, I have a problem on line #52. Can someone help me? I tried the one solution that was posted in here but its not working. Thankyou

"C:\Users\PycharmProjects\AI\venv\Scripts\python.exe" "C:/Users/PycharmProjects/AI/trafficpredictionMLAB3.py"
Mean absolute error: 7.42
Traceback (most recent call last):
  File "C:\Users\PycharmProjects\AI\trafficpredictionMLAB3.py", line 52, in <module>
    test_datapoint_encoded[i] = int(label_encoder[count].transform(test_datapoint[i]))
  File "C:\Users\PycharmProjects\AI\venv\lib\site-packages\sklearn\preprocessing\_label.py", line 133, in transform
    y = column_or_1d(y, warn=True)
  File "C:\Users\PycharmProjects\AI\venv\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\PycharmProjects\AI\venv\lib\site-packages\sklearn\utils\validation.py", line 864, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape () instead.

Process finished with exit code 1
